format = "Agent"
version = "1.0"
name = "Task-Agnostic"


################################################################################
# Perception
################################################################################

[Perception]
protocol = "HyperFilter"

[Perception.params]
dt = 12 # Time window, ~500ms
h  = 5  # Number of hyper particles

[Perception.params.pf]
protocol = "AdaptiveParticleFilter"
params = {particles = 5} # Number of inner particles

################################################################################
# Planning
################################################################################

[Planning]
protocol = "CollisionCounter"

[Planning.params]
mat = "Light"
cooldown = 18
tick_rate = 1

################################################################################
# Attention
################################################################################

[Attention]
protocol = "UniformProtocol"

[Attention.params]
moves = 24

################################################################################
# Memory
################################################################################

[Memory]
protocol = "HyperResampling"

[Memory.params]
tau = 1.0
perception = { "protocol" = "ModuleRef", "params" = { "ref" = "Perception" } }

[Memory.params.fitness]
protocol = "MLLFitness"

[Memory.params.kernel]
protocol = "SplitMergeKernel"

[Memory.params.kernel.params]
restructure_prob = 0.5
heuristic = { protocol = "UniformSplitMerge" }
