[WorldModel]
protocol = "InertiaWM"

[WorldModel.params]
object_rate = 8.0
area_width = 720.0
area_height = 480.0
birth_weight = 0.01
single_size = 5.0
single_noise = 2.0
single_cpoisson_log_penalty = -3000.0
stability = 0.80
vel = 4.5
force_low = 10.0
force_high = 15.0
material_noise = 0.01
ensemble_var_shift = 10.0
