name = "AdaptiveGorilla"
uuid = "809448cc-0cd5-4a4e-b13f-cd5c519b7131"
authors = ["mario <mbelledonne@gmail.com>"]
version = "0.1.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FunctionalCollections = "de31a74c-ac4f-5751-b3fd-e18cd04993ca"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
GenParticleFilters = "56b76ac4-72ef-411e-b419-6d312ed86a6f"
GenRFS = "56ab6c88-a2ab-44ec-99ca-7b9069b439c2"
Gen_Compose = "c1ef4dca-b0a6-4a35-b24b-46cbf3979a16"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
MOTCore = "5c8d5ed6-9297-4b4e-8c36-1078fadcc608"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
Distributions = "0.25.113"
Gen = "0.4.7"
GenRFS = "0.1.0"
PProf = "3.2.0"
ProgressMeter = "1.10.4"
SpecialFunctions = "2.5.1"
Statistics = "1.11.1"
UnicodePlots = "3.7.2"
