format = "Agent"
version = "1.0"
name = "Multi-Granular Optimization"


################################################################################
# Perception
################################################################################

[Perception]
protocol = "HyperFilter"

[Perception.params]
dt = 12 # Time window, ~1.5s
h  = 5  # Number of hyper particles

[Perception.params.pf]
protocol = "AdaptiveParticleFilter"
params = {particles = 5} # Number of inner particles

################################################################################
# Planning
################################################################################

[Planning]
protocol = "CollisionCounter"

[Planning.params]
mat = "Light"  # Color of targets
cooldown = 12   # Cooldown between hits (prevents overcounting)
tick_rate = 1  # How often to evaluate counting (same as perception)

################################################################################
# Attention
################################################################################

[Attention]
protocol = "AdaptiveComputation"

[Attention.params]
itemp = 8.0                          # importance temperature
base_steps = 8                        # Minimum load
load = 16                             # Maximum load
buffer_size = 2000                    # Size of task-relevance heatmap
map_metric_weights = [0.1, 0.1, 0.8]  # Distance function for task-relevance
nns = 20

################################################################################
# Memory
################################################################################

[Memory]
protocol = "HyperResampling"

[Memory.params]
tau = 1.0   # Temporature for resampling hyper chains
perception = { "protocol" = "ModuleRef", "params" = { "ref" = "Perception" } }

[Memory.params.fitness]
protocol = "MhoFitness"

[Memory.params.fitness.params]
beta = 300.0             # Log-regularization constant for MLL component
complexity_mass = 0.50   # Slope of exponential irrelevant complexity curve
complexity_factor = 0.8  # Sensitivity to irrelevant representations
att = { "protocol" = "ModuleRef", "params" = { "ref" = "Attention" } }

[Memory.params.kernel]
protocol = "SplitMergeKernel"

[Memory.params.kernel.params]
restructure_prob = 0.8   # Probability that restructuring occurs

[Memory.params.kernel.params.heuristic]
protocol = "MhoSplitMerge"

[Memory.params.kernel.params.heuristic.params]
att = { "protocol" = "ModuleRef", "params" = { "ref" = "Attention" } }
