[WorldModel]
protocol = "InertiaWM"

[WorldModel.params]
object_rate = 8.0
area_width = 720.0
area_height = 480.0
birth_weight = 0.10
single_size = 5.0
single_noise = 1.5
single_cpoisson_log_penalty = -3000.0
stability = 0.70
vel = 4.5
force_low = 5.0
force_high = 10.0
ang_acc = 1.0
material_noise = 0.01
ensemble_force = 10.0
ensemble_var_shift = 5.0
