[WorldModel]
protocol = "InertiaWM"

[WorldModel.params]
object_rate = 8.0
area_width = 720.0
area_height = 480.0
birth_weight = 0.01
single_size = 5.0
single_cpoisson_log_penalty = -3000.0
stability = 0.80
vel = 4.5
force_low = 3.0
force_high = 10.0
ang_acc = 5.0
ensemble_force = 4.5
ensemble_var_shift = 5.0
single_noise = 0.5
material_noise = 0.01
